name: maxiprot
channels:
  - conda-forge
  - bioconda
dependencies:
  - miniprot
  - pip
  - python>=3.10
  - samtools
  - pip:
      - biopython
      - numpy
      - pandas
      - pyfaidx
      - rich
      - git+https://github.com/Adamtaranto/maxiprot.git
